consentadmin-main:
    path:       /
    defaults:   { _controller: 'SimpleSAML\Module\consentadmin\Controller\ConsentAdmin::main' }
    methods: [GET]

consentadmin-logout:
    path:       /logout
    defaults:   { _controller: 'SimpleSAML\Module\consentadmin\Controller\ConsentAdmin::logout' }
    methods: [GET]
